 (focus AGENT)
 (set-break control-astar)
; (set-break exec_act)
 (focus ASTAR)
 (set-break astar-go)
 (set-break astar-ok)
; (set-break astar-clean1)
; (set-break astar-clean2)
; (focus ASTAR-ALGORITHM)
; (set-break close-empty)
; (set-break post-astar)
; (set-break achieved-goal)
; (focus POSTASTAR)
; (set-break execute-exec-star)
; (set-break go-forward-apply-south)
; (set-break go-forward-exec-south)
;(focus PUNTEGGI)
;(set-break best-cell)