(focus AGENT)
(set-break turno0)
(set-break control-astar)
(set-break control-exit)
(set-break move)
(focus PUNTEGGI)
(set-break best-cell)
(focus EXIT)
(set-break exit-go)
(set-break exit-ok)
(set-break exit-clean1)
(focus ASTAR)
(set-break astar-go)
(set-break astar-ok)
(set-break astar-clean2)
(set-break astar-clean3)
(focus ASTAR-ALGORITHM)
(set-break close-empty)
(set-break post-astar)
(set-break achieved-goal)
(focus POSTASTAR)
(set-break execute-exec-star)
; (set-break clean-astar1)
; (set-break clean-astar2)
; (set-break clean-astar3)