(load "1_main.clp")
(load "2_initial_map.clp")
(load "3_env.clp")
(load "4_actual_map.clp")
(load "5_agent.clp")
(load "6_init_punteggi.clp")
(load "01_time.clp")
(load "02_inform.clp")
(load "03_punteggi.clp")
(load "04_exit.clp")
(load "05_astar.clp")
(load "9_new.clp")
(load "8_a_star.clp")
(load "10_post-astar.clp")
(reset)
(batch "C:/Users/Alessandro/Documents/NetBeansProjects/ialab/Monitor1213/ale-break1.bat")